### ISSUE TITLE
Strange answer, please help

### ISSUE THREAD

**Issue by Pascal66** [gunmetal313/mfocuino#1]
1 NFC device(s) found:
debug   libnfc.driver.pn532_uart    Attempt to open: /dev/ttyUSB0 at 230400 baud.
debug   libnfc.bus.uart Serial port speed requested to be set to 230400 baud.
debug   libnfc.chip.pn53x   Diagnose
debug   libnfc.chip.pn53x   Timeout value: 500
debug   libnfc.bus.uart TX: 55 55 00 00 00 00 00 00 00 00 00 00 00 00 00 00 
debug   libnfc.chip.pn53x   SAMConfiguration
debug   libnfc.chip.pn53x   Timeout value: 1000
debug   libnfc.bus.uart TX: 00 00 ff 03 fd d4 14 01 17 00 
debug   libnfc.bus.uart RX: 98 80 98 80 1e 66 
error   libnfc.chip.pn53x   Unexpected PN53x reply!
error   libnfc.driver.pn532_uart    pn53x_check_communication error
debug   libnfc.chip.pn53x   InRelease
debug   libnfc.bus.uart TX: 00 00 ff 03 fd d4 52 00 da 00 
debug   libnfc.bus.uart RX: 80 06 60 cc e0 06 
error   libnfc.chip.pn53x   Unexpected PN53x reply!
debug   libnfc.general  Unable to open "pn532_uart:/dev/ttyUSB0".
nfc_open failed for pn532_uart:/dev/ttyUSB0
android@builduntu-VM:~/libnfc$

**Comment by gunmetal313** [comment]
Hello
What nfc device?

**Comment by gunmetal313** [comment]
What os?

**Comment by Pascal66** [comment]
Hello !
The device is : https://www.seeedstudio.com/item_detail.html?p_id=1804
I2C bus version.
I've tried the mifareclassic reader wich is working with the original PN532 library from seeed.
But your are using the old I2C version from Adafruit wich isnt working here coz the need of irq.
Thank you for your answer in an old project

**Comment by Pascal66** [comment]
And ubuntu as os under virtualbox usind ftdi and USB00 as com port.
"Regular" examples for FTDI work.
So it's a problem with the two new "hacked" function I think.
I'm loose after tried 3 differents versions.
Hope you  can help me
